# Generated by Django 3.0.5 on 2021-02-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210217_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='caption',
            new_name='name',
        ),
    ]
